language: python
python:
- "2.7"
- "3.6"
- "3.7"

git:
  depth: false

os:
- linux
#- windows

install:
- pip install pytest pytest-cov coverage

script:
- pytest -vv --cov-report term-missing:skip-covered --cov=grep/

